# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Minhaz"
subtitle: "See the world through my eyes!"
author: "Minhaz"
header:
 title: "Photography"
 subtitle: "by Minhaz"
footer:
 name: "Hey there, my name is Minhaz"
 bio: ""
 github: ""
web_design: ""
social_urls:
  twitter: "https://www.twitter.com/minhazav"
  instagram: "https://www.instagram.com/mebjas"
  linkedin: "https://in.linkedin.com/in/minhazav"
  github: "https://www.github.com/mebjas"
